language: node_js
before_install:
- phantomjs --version
- npm install -g grunt-cli grunt-init bower
- bower install
branches:
  only:
  - master
node_js:
- '0.10'
before_script:
- git config --global user.name "Jichao Ouyang"
- git config --global user.email "oyanglulu@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/jcouyang/jcouyang.github.com.git"
script:
- grunt-init config
- npm test
after_success:
- node crawl
- grunt sitemap
- git remote add blogist $REPO_URL
- git checkout -B master
- git rm .travis.yml -f
- git add sitemap.xml index.html javascripts bower_components -f
- git add CNAME
- git add blog gist rss.xml
- git commit -am 'publi:ship:'
- git push blogist master -f -q
env:
  global:
    secure: Tiyeu3EUl4FRTmadyhRa2Jcsyz38pU8MxSel3nHe0Mi9xkubWmmlTzmwrs8VWJlOB/5SnHJyk9daaUus5xdxZmFCuuQhN5oTgbTuSs0D96YPr0b2boA53F81GQ+gErjcju0B9BKS8OLJzhwi5ld7txE56fZU6YLehB/JEr+hmLU=
