language: node_js
before_install:
- phantomjs --version
- npm install -g grunt-cli grunt-init bower
- bower install
branches:
  only:
  - master
node_js:
- '0.10'
before_script:
- git config --global user.name "Jichao Ouyang"
- git config --global user.email "oyanglulu@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/jcouyang/jcouyang.github.com.git"
script:
- npm test
after_success:
- node crawl
- grunt sitemap
- git remote add blogist $REPO_URL
- git checkout -B master
- git rm .travis.yml -f
- git add sitemap.xml index.html javascripts bower_components -f
- git add CNAME
- git add gist atom.xml -f
- git commit -am 'publi:ship:'
- git push blogist master -f -q
env:
  global:
    secure: TeP8dvtRej2ejMIFlK6SVuzFlaQOQDggQuFa/eJo9mf7FU5ygDiKEErESdmSXbZbUX9VQVPSGbUnLPcdsSGCGoh9egxcOikvPlDCnsVlfx0iVnrCD7p7lJpJy4gMU9xcZeZfnJqE95imtLpima4MpINKnmZFy02gWmOXdlVjUlI=
