language: node_js
before_install:
    - phantomjs --version
    - npm install -g grunt-cli grunt-init
branches:
  only:
  - master
node_js:
- '0.10'
before_script:
- git config --global user.name "{{author_name}}"
- git config --global user.email "{{author_email}}"
- export REPO_URL="https://$GH_TOKEN@{{repository|replace("https://", "")}}"

script:
    {% if settings %}
    - grunt-init config
    {% endif %}
    - npm test
after_success:
{% if settings %}
- grunt sitemap
- git remote add blogist $REPO_URL
- git add sitemap.xml index.html
- git commit -m 'publi:ship:'
- git checkout -B {{branch}}
- git push blogist {{branch}} -f -q
- node crawl
- git add gist rss.xml
- git checkout -B {{branch}}
- git push blogist {{branch}} -f -q
{% endif%}
